# Generated by Django 4.2.6 on 2023-11-08 14:18

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encaminhamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IgnorarMes',
            new_name='DiasAusencia',
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 11, 18, 41, 588480)),
        ),
    ]
