# Generated by Django 4.2.6 on 2023-10-31 02:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(default=datetime.datetime(2023, 10, 30, 23, 4, 50, 583651))),
                ('link', models.CharField(max_length=256)),
                ('tramite', models.IntegerField()),
                ('classificacao', models.CharField(max_length=256)),
                ('modulo', models.CharField(max_length=256)),
                ('topico', models.CharField(max_length=256)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncaminhamentoIncorreto',
            fields=[
                ('encaminhamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='encaminhamentos_incorretos.encaminhamento')),
                ('desc_encaminhamento', models.TextField(max_length=500)),
                ('validado', models.BooleanField(default=False)),
                ('concordancia', models.BooleanField(default=False)),
                ('analise_analista', models.TextField(max_length=500)),
            ],
            bases=('encaminhamentos_incorretos.encaminhamento',),
        ),
        migrations.CreateModel(
            name='IgnorarMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(max_length=12)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
