# Generated by Django 4.2.6 on 2023-10-31 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos_incorretos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 9, 21, 56, 135276)),
        ),
        migrations.AlterField(
            model_name='encaminhamentoincorreto',
            name='analise_analista',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
