# Generated by Django 4.2.6 on 2023-10-31 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos_incorretos', '0002_alter_encaminhamento_datahora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='ss',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 16, 23, 50, 525249)),
        ),
    ]
