# Generated by Django 4.2.6 on 2023-11-01 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos_incorretos', '0004_alter_encaminhamento_datahora_alter_ignorarmes_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encaminhamento',
            name='ss',
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 11, 21, 25, 903939)),
        ),
    ]
