# Generated by Django 4.2.6 on 2023-11-03 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos_incorretos', '0005_remove_encaminhamento_ss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encaminhamentoincorreto',
            old_name='analise_analista',
            new_name='justificativa',
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 7, 41, 28, 101521)),
        ),
    ]
