# Generated by Django 4.2.6 on 2023-11-03 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos_incorretos', '0006_rename_analise_analista_encaminhamentoincorreto_justificativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamento',
            name='datahora',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 7, 41, 42, 23578)),
        ),
    ]
